-
  - 공개키와 대칭키의 차이는 무엇인가요
  - |
    둘 다 암호화와 복호화에 사용되는 키 알고리즘이며 어떤 방식으로 키를 이용하는가에 차이를 두고 있음

    # 대칭키

    먼저 대칭키의 경우 하나의 키만을 사용해 암호화 및 복호화를 진행하는 방식임

    따라서 key generation 및 암복호화 속도는 좀 빠르겠지만

    키 교환 시 탈취될 위험이 있다는 단점이 있음

    # 공개키

    이와는 달리 공개키의 경우 공개키와 비밀키 두 개를 이용해서 암호화 및 복호화를 진행하는 방식임

    공개키와 비밀키라는 두 개의 키를 생성한 후, 공개키를 이용해 암호화 비밀키를 이용해 복호화를 진행하게 됨

    속도는 조금 느리지만 키 교환 시 탈취될 염려가 없다는 것이 장점

-
  - 방화벽이 무엇인가요?
  - |
    네트워크를 지나는 데이터에 대해 검열을 하는 소프트웨어 또는 하드웨어임

    방화벽을 통과할 수 있는 데이터와 그렇지 않은 데이터를 구분하는 rule set을 사전에 정의해야 하며

    rule set은 IP와 PORT를 기준으로 설정이 가능함

-
  - IPS가 무엇인가요?
  - |
    # 침입탐지시스템은

    시스템에 대한 원치 않는 조작을 탐지하는 시스템

    네트워크 기반과 호스트 기반 두 종류가 있으며, 각각 다음과 같음

    ### 네트워크 기반

    네트워크 기반의 IPS인 NIPS는

    스위치와 같은 장비에 설치되어 패킷을 분석하고 침입을 탐지하는 IPS임

    호스트 서버에 설치되는 것이 아니기에, TLS와 같이 암호화된 패킷의 경우는 탐지가 불가능함

    ### 호스트 기반

    호스트 기반의 IPS인 HIPS는

    말 그대로 호스트에 설치되어 동작하는 IPS이며

    실제 공격이 이루어질 때 탐지를 하는 IPS임

-
  - IDS가 무엇인가요?
  - |
    # 침입방지시스템은

    pattern matching을 통해 패킷을 분석하고

    정상적인 패킷이 아닌 경우에는 방화벽을 이용해 차단하는 시스템임

    물론 오탐이 발생될 가능성이 있으나

    실시간으로 pattern을 이용해 대응이 가능하다는 장점이 있음

-
  - IPS와 IDS의 차이점이 무엇인가요?
  - |
    IPS같은 경우는 탐지만을 목적으로 하는 장비이며

    IDS는 방화벽과 함께 설치되어 탐지 및 방어와 같은 대응까지 가능하다는 특징이 있음
