-
  - 공개키와 대칭키의 차이는 무엇인가요
  - |
    둘 다 암호화와 복호화에 사용되는 키 알고리즘이며 어떤 방식으로 키를 이용하는가에 차이를 두고 있음

    # 대칭키

    먼저 대칭키의 경우 하나의 키만을 사용해 암호화 및 복호화를 진행하는 방식임

    따라서 key generation 및 암복호화 속도는 좀 빠르겠지만

    키 교환 시 탈취될 위험이 있다는 단점이 있음

    # 공개키

    이와는 달리 공개키의 경우 공개키와 비밀키 두 개를 이용해서 암호화 및 복호화를 진행하는 방식임

    공개키와 비밀키라는 두 개의 키를 생성한 후, 공개키를 이용해 암호화 비밀키를 이용해 복호화를 진행하게 됨

    속도는 조금 느리지만 키 교환 시 탈취될 염려가 없다는 것이 장점
